language: node_js

node_js:
  - "9"
  - "8"
  - "7"
  - "6"

os:
  - linux
  - osx

services:
  - docker

jobs:
  include:
      stage: deploy
      node_js: "9"
      os: "linux"
      before_deploy:
        - npm install
        - npm run deploy -- --r $DEPLY_URL